[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/*"
  excludedPath = ["/.netlify/*", "/api/*"]
  function = "auth"
